# Server Port
server:
  port: 8080

# Spring
spring:
  profiles:
    active: dev

  # Jpa 
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

  # H2
  h2:
    console:
      enabled: true
      path: /h2/dev_db

  #Datasource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/short_url_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    username: test
    password: 1234

  # Thymeleaf
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    cache: false # Dev Only

  resources:
      static-locations: classpath:/static/
      cache:
        period: 0

  # Devtool
  devtools:
    livereload:
      enabled: true
